### ISSUE TITLE
inspecting steam links is no more working

### ISSUE THREAD

**Issue by Snake4life** [araynimax/phoskin#3]
Issue:
you try to inspect a skin from steam inspect link [ !i ] but its failing

Logs:
[SM] Exception reported: Could not retrieve value for key 'stickers'
[SM] Blaming: phoskin.smx
[SM] Call stack trace:
[SM]   [0] JSONObject.Get
[SM]   [1] Line 376, .\generator.sp::OnCSGOFloatResponse

it looks like this issue is related to this: https://github.com/csgofloat/inspect/issues/131

**Comment by araynimax** [comment]
This is definitely related to the linked problem. 

One solution might be that we need to host the csgofloatapi ourselves (https://github.com/csgofloat/inspect#how-to-install) But I cant confirm that this really solves the issue.

I will add a way to change the api endpoint to a custom endpoint via a cvar.

**Comment by Snake4life** [comment]
I can confirm setting up a selfhosted csgofloatapi solves the issue, the cvar should support http and/or https endpoints

thank you very much for your awesome work!

**Comment by araynimax** [comment]
I will let this issue open until I publish the fix

**Comment by araynimax** [comment]
Its implemented. Head to https://github.com/araynimax/phoskin/releases/ and get the new version.

The convar is named `pho_inspect_url` and only will be read on plugin start.
Putting the cvar into your server.cfg or similar should work.

Read more [here](https://github.com/araynimax/phoskin/blob/8b9fa56583294ae0fc5de11036bd91fca35fe8b8/README.md#important)

**Comment by araynimax** [comment]
Closed
