### ISSUE TITLE
Instalation issues

### ISSUE THREAD

**Issue by henriquelbsouza** [araynimax/phoskin#5]
Hi! I am trying to install into a running csgo server, I have already installed metamod, sourcemod and pasted your plugin into csgo folder on the server instance.

I did the same for ptah and ripext dependencies. But I had no lucky when trying to use the !gen command. Simply doesn't work :/

Is there anything else I need to do?

meta list:
```] meta list
  [01] SourceMod (1.11.0.6934) by AlliedModders LLC
  [02] CS Tools (1.11.0.6934) by AlliedModders LLC
  [03] SDK Tools (1.11.0.6934) by AlliedModders LLC
  [04] SDK Hooks (1.11.0.6934) by AlliedModders LLC
```

sm list: 
```] sm plugins
 "Client Preferences" (1.11.0.6934) by AlliedModders LLC
 "Basic Info Triggers" (1.11.0.6934) by AlliedModders LLC
 "Basic Comm Control" (1.11.0.6934) by AlliedModders LLC
 "Anti-Flood" (1.11.0.6934) by AlliedModders LLC
 "Reserved Slots" (1.11.0.6934) by AlliedModders LLC
 "Basic Commands" (1.11.0.6934) by AlliedModders LLC
 "Basic Ban Commands" (1.11.0.6934) by AlliedModders LLC
 "Player Commands" (1.11.0.6934) by AlliedModders LLC
 "Fun Votes" (1.11.0.6934) by AlliedModders LLC
 "Admin Help" (1.11.0.6934) by AlliedModders LLC
To see more, type "sm plugins 11"

] sm plugins 11
 "Fun Commands" (1.11.0.6934) by AlliedModders LLC
 "Basic Votes" (1.11.0.6934) by AlliedModders LLC
 "Nextmap" (1.11.0.6934) by AlliedModders LLC
 "Admin Menu" (1.11.0.6934) by AlliedModders LLC
 "Sound Commands" (1.11.0.6934) by AlliedModders LLC
 "Basic Chat" (1.11.0.6934) by AlliedModders LLC
 "Admin File Reader" (1.11.0.6934) by AlliedModders LLC
```

Not sure how to proceed... 

Thanks in advance!

**Comment by henriquelbsouza** [comment]
This is a fresh csgo server running on ubuntu. I can change everything if needed :)

**Comment by araynimax** [comment]
Hello,

Thanks for reaching out. However, please note that GitHub issues are meant for reporting bugs and issues related to the phoskins plugin, and not for general support. Additionally I don't have the resources to provide individual installation support to every user.

If you encounter any problems or bugs related to phoskins, feel free to open an issue with as much information as possible.

In your case, it's possible that the issue you're experiencing with the plugin not appearing in the list is related to one of the dependencies not loading properly. Please check the dependencies and verify that they have been loaded correctly.
Additionally, you may want to check your server logs for any errors that could help you get closer to solving the problem.

Good luck getting it to work, and let me know if you have any other bug reports or issues related to phoskins.

Best regards

**Comment by henriquelbsouza** [comment]
Thanks for the reply, I was about to say that I manage to fix right now :D

It was an issue with one of the dependencies not working.

Thanks again, and no worries :)
