### ISSUE TITLE
!i Error: Could not fetch item information!

### ISSUE THREAD

**Issue by pr0stre1** [araynimax/phoskin#6]
I just set pho_inspect_url to inspect.pricempire.com API but still get error and fetching item information not working by link

**Server logs**
[SM] Value of cvar "pho_inspect_url": "https://inspect.pricempire.com"

I still get error

[PHOSKIN] Fetching item information...
[PHOSKIN] Error: Could not fetch item information!

**Comment by araynimax** [comment]
Please provide **Server Logs** and not your chat logs please.

**Comment by araynimax** [comment]
I assume you have read the "Important" section in the readme?

There Ive said that the cvar has to be set before starting the plugin. Did you stick to it.

**Comment by pr0stre1** [comment]
Yes, i'm not sure what execution sequence of files, but i have sm_cvar pho_inspect_url "https://inspect.pricempire.com" in my server.cfg file, after setting it, i restarted server and still get error.

Which one log do you want to see? /csgo/addons/sourcemod/logs errors file and log file do not have any issues, i can provide any log file you request

**Comment by araynimax** [comment]
Please use normal way of setting cvars.

Like in the game itself.

Just put pho_inspect_url "https://inspect.pricempire.com" into it

**Comment by pr0stre1** [comment]
I've tested it with normal pho_inspect_url and nothing changed

**Comment by araynimax** [comment]
Then please provide your server console output.

**Comment by pr0stre1** [comment]
[L000_000_000_000_27015_202305071939_000.log](https://github.com/araynimax/phoskin/files/11415851/L000_000_000_000_27015_202305071939_000.log)
[L000_000_000_000_27015_202305071939_001.log](https://github.com/araynimax/phoskin/files/11415852/L000_000_000_000_27015_202305071939_001.log)
[L000_000_000_000_27015_202305071942_000.log](https://github.com/araynimax/phoskin/files/11415864/L000_000_000_000_27015_202305071942_000.log)


[L000_000_000_000_27015_202305071942_000.log](https://github.com/araynimax/phoskin/files/11415867/L000_000_000_000_27015_202305071942_000.log)
[L000_000_000_000_27015_202305071942_001.log](https://github.com/araynimax/phoskin/files/11415868/L000_000_000_000_27015_202305071942_001.log)

**Comment by pr0stre1** [comment]
Do you have any suggestions?

**Comment by MEOWLORD** [comment]
I'm getting similar, it's not even working on other peoples servers for me

**Comment by Lines08** [comment]
Changing it in the "main.sp" file and re-compiling worked for me!
somehow just adding it into the server.cfg wasn't enough even tough the console says it changed correct.

**Comment by araynimax** [comment]
@Lines08 

> Changing it in the "main.sp" file and re-compiling worked for me! somehow just adding it into the server.cfg wasn't enough even tough the console says it changed correct.

Very interesting... thank you for the info. I don't have time at the moment testing things myself.

Would you mind testing it with the potential fix I’ve pushed?

Use the artifact from the job please:
https://github.com/araynimax/phoskin/actions/runs/4942994543

**Comment by araynimax** [comment]
@pr0stre1 Sorry for the late reply.
Currently, I unfortunately have no time to test things myself. I hope that the problem had to do with the readout of the CVAR and should be fixed with my latest commit. (If someone confirms that it will work now, I will push a new release) You can test it with artifact of the latest build job (Read my previous comment).

**Comment by pr0stre1** [comment]
No problem. I have tested your fix, now problem solved and all works fine, thank you

**Comment by araynimax** [comment]
I'm glad to hear that. Have fun :)

**Comment by araynimax** [comment]
New [release](https://github.com/araynimax/phoskin/releases/tag/1.2.2) published - issue closed

**Comment by PadowYT2** [comment]
Having same issue currently, running v1.2.2, https://csgo.padow.ru
