### ISSUE TITLE
Dropped weapons disappear

### ISSUE THREAD

**Issue by MageSneaky** [araynimax/phoskin#9]
**Describe the bug**
Walking over dropped weapons makes them disappear. Only if holding same type example ak47

**To Reproduce**
Not sure if it matters but i am running Deathmatch. Drop a gun on the ground and then get the same weapon in your hands/inventory and walk over the weapon on the ground.

**Expected behavior**
I mean for the item to not disappear

**Additional context**
Deathmatch server, using !ws, !knife, !gloves, Using phoskins version 1.2.1

**Comment by araynimax** [comment]
Wont fix because of needed redevelopment for cs2.

I don't have any time to start the development for cs2.
See #8
